---
# tasks file for roles/java11
- name: Install Java-11
  yum:
    name: java-11-openjdk
    state: present

- name: Set JAVA_HOME if configured
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644

